on:
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Hello
    steps:
    - uses: actions/checkout@v3
    - run: gh pr comment $PR_URL --body "yay II!"
      env:
        GITHUB_TOKEN: ${{ secrets.DEPENDABOT_PUSH_TOKEN }}
        GH_TOKEN: ${{ secrets.DEPENDABOT_PUSH_TOKEN }}
        PR_URL: ${{github.event.pull_request.html_url}}

