on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ^1.20.3
    - uses: goto-bus-stop/setup-zig@v2
    - run: ./release.sh
    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: release/*
    - name: Tag new releases
      id: tag
      uses: anothrNick/github-tag-action@1.61.0 # Don't use @master unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true
    - name: add version number to release files
      run: |
          mv release/s3db-linux-amd64-glibc.sqlite-ext.so.gz release/s3db-${{ steps.tag.outputs.tag }}-linux-amd64-glibc.sqlite-ext.so.gz
          mv release/s3db-linux-arm-glibc.sqlite-ext.so.gz release/s3db-${{ steps.tag.outputs.tag }}-linux-arm-glibc.sqlite-ext.so.gz
          mv release/s3db-linux-arm64-glibc.sqlite-ext.so.gz release/s3db-${{ steps.tag.outputs.tag }}-linux-arm64-glibc.sqlite-ext.so.gz
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.tag.outputs.tag }}
        prerelease: false
        files: |
          release/s3db-${{ steps.tag.outputs.tag }}-linux-amd64-glibc.sqlite-ext.so.gz
          release/s3db-${{ steps.tag.outputs.tag }}-linux-arm-glibc.sqlite-ext.so.gz

