name: Bump version and release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.tag.outputs.new_tag}}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.61.0 # Don't use @master unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true

  release:
    runs-on: ubuntu-latest
    needs: [tag]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20.2

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - uses: goto-bus-stop/setup-zig@v2

      - name: Build
        run: |
          mkdir release
          cd sqlite
          go generate && mv s3db.so ../release/s3db-${{ needs.tag.outputs.tag }}-linux-amd64-glibc.sqlite-ext.so
          CGO_ENABLED=1 GOOS=linux GOARCH=arm CC="zig cc -target arm-linux-glibc" go generate && mv s3db.so ../release/s3db-${{ needs.tag.outputs.tag }}-linux-arm-glibc.sqlite-ext.so
          cd ../release
          gzip -9 *

      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ needs.tag.outputs.tag }}
          prerelease: false
          files: |
            release/s3db-${{ needs.tag.outputs.tag }}-linux-arm-glibc.sqlite-ext.so.gz
            release/s3db-${{ needs.tag.outputs.tag }}-linux-amd64-glibc.sqlite-ext.so.gz

